obstacle_range: 15
raytrace_range: 20
# footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
inflation_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_sensor_link, data_type: LaserScan, topic: /steer_bot/laser/scan, marking: true, clearing: true}
